package com.dibi.livepulllocal.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dibi.livepulllocal.entity.User;
import com.dibi.livepulllocal.entity.Gao;
import com.dibi.livepulllocal.entity.GaoId;

import com.dibi.livepulllocal.greendao.UserDao;
import com.dibi.livepulllocal.greendao.GaoDao;
import com.dibi.livepulllocal.greendao.GaoIdDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig gaoDaoConfig;
    private final DaoConfig gaoIdDaoConfig;

    private final UserDao userDao;
    private final GaoDao gaoDao;
    private final GaoIdDao gaoIdDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        gaoDaoConfig = daoConfigMap.get(GaoDao.class).clone();
        gaoDaoConfig.initIdentityScope(type);

        gaoIdDaoConfig = daoConfigMap.get(GaoIdDao.class).clone();
        gaoIdDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        gaoDao = new GaoDao(gaoDaoConfig, this);
        gaoIdDao = new GaoIdDao(gaoIdDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Gao.class, gaoDao);
        registerDao(GaoId.class, gaoIdDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        gaoDaoConfig.clearIdentityScope();
        gaoIdDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GaoDao getGaoDao() {
        return gaoDao;
    }

    public GaoIdDao getGaoIdDao() {
        return gaoIdDao;
    }

}
